version: "3"
networks: {}
volumes: 
  bitcoin-miner0: 
services:
  
  bitcoin0:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: Dockerfile 
  # image: bitcoin     
    restart: unless-stopped
    stop_grace_period: 60s
    container_name: bitcoin0
    environment:
      - SIGNETCHALLENGE=512102f7561d208dd9ae99bf497273e16f389bdbd6c4742ddb8e6b216e64fa2928ad8f51ae
      - TRIPLET=x86_64-linux-gnu
      - UACOMMENT=MutinyWallet-0
      - RPCUSER=bitcoin
      - RPCPASSWORD=bitcoin
      - ZMQPUBRAWBLOCK=tcp://0.0.0.0:28332
      - ZMQPUBRAWTX=tcp://0.0.0.0:28333
      - ZMQPUBHASHBLOCK=tcp://0.0.0.0:28334
      - RPCBIND=0.0.0.0:38332
      - RPCALLOWIP=0.0.0.0/0
      - WHITELIST=0.0.0.0/0
      - BLOCKPRODUCTIONDELAY=1
      - MINERENABLED=0
      - SIGNET_BLOCKTIME=30
    # - MINE_GENESIS=1
    #  - EXTERNALIP=1.1.1.1:38333,2.2.2.2:38333
      - ADDNODE=45.79.52.207:38333
      # - ONIONPROXY=tor:9050
      # - TORPASSWORD=hello
      # - TORCONTROL=tor:9051
      # - ADDNODE=${ADDNODE}
      # - NBITS=${NBITS}
      # - I2PSAM=${I2PSAM:-""}
      - OTHER_BITCOIN_ARGS=
    expose: 
      - "28332"
      - "28333"
      - "28334"
      - "38332"
      - "38333" 
    volumes:
      - "bitcoin-miner0:/root/.bitcoin/"